// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "categories"

// Category mapped from table <categories>
type Category struct {
	CategoryID   int64 `gorm:"primaryKey"`
	CategoryName string
	Products     []Product `gorm:"many2many:product_category;foreignKey:CategoryID;joinForeignKey:CategoryID;References:ProductID;joinReferences:ProductID"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
