// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrdertab = "ordertabs"

// Ordertab mapped from table <ordertabs>
type Ordertab struct {
	OrderID int64
	UserID  int64
}

// TableName Ordertab's table name
func (*Ordertab) TableName() string {
	return TableNameOrdertab
}
