// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderDetail = "order_detail"

// OrderDetail mapped from table <order_detail>
type OrderDetail struct {
	OrderID   int64    `gorm:"primaryKey"`
	ProductID int64    `gorm:"primaryKey"`
	Product   Product  `gorm:"foreignkey:ProductID;references:ProductID"`
	Ordertab  Ordertab `gorm:"foreignkey:OrderID;references:OrderID"`

	//Ordertab Ordertab
}

// TableName OrderDetail's table name
func (*OrderDetail) TableName() string {
	return TableNameOrderDetail
}
